#include <bits/stdc++.h>
#include <atcoder/all>

using namespace std;
using namespace atcoder;

using ll = long long;

const ll MOD = 998244353;

void solve(ll N, ll M, vector<ll> a, vector<ll> b){

}

// Generated by 2.14.0 https://github.com/kyuridenamida/atcoder-tools
int main(){
    ll N;
    scanf("%lld", &N);
    ll M;
    scanf("%lld", &M);
    vector<ll> a(M);
    vector<ll> b(M);
    for(int i = 0 ; i < M ; i++){
        scanf("%lld", &a[i]);
        scanf("%lld", &b[i]);
    }
    solve(N, M, move(a), move(b));
    return 0;
}
