#include <bits/stdc++.h>
#include <atcoder/all>

using namespace std;
using namespace atcoder;

using ll = long long;

const ll MOD = 998244353;


// Generated by 2.14.0 https://github.com/kyuridenamida/atcoder-tools
int main(){
    // Failed to predict input format
    return 0;
}
