#include <bits/stdc++.h>
#include <atcoder/all>

using namespace std;
using namespace atcoder;

using ll = long long;


void solve(ll N, ll M, vector<ll> H){

}

// Generated by 2.14.0 https://github.com/kyuridenamida/atcoder-tools
int main(){
    ll N;
    scanf("%lld", &N);
    ll M;
    scanf("%lld", &M);
    vector<ll> H(N);
    for(int i = 0 ; i < N ; i++){
        scanf("%lld", &H[i]);
    }
    solve(N, M, move(H));
    return 0;
}
