#include <bits/stdc++.h>
#include <atcoder/all>

using namespace std;
using namespace atcoder;

using ll = long long;


void solve(string S){

}

// Generated by 2.14.0 https://github.com/kyuridenamida/atcoder-tools
int main(){
    string S;
    cin >> S;
    solve(S);
    return 0;
}
