#include <bits/stdc++.h>
#include <atcoder/all>

using namespace std;
using namespace atcoder;

using ll = long long;


void solve(ll N, vector<ll> a){

}

// Generated by 2.14.0 https://github.com/kyuridenamida/atcoder-tools
int main(){
    ll N;
    scanf("%lld", &N);
    vector<ll> a(N);
    for(int i = 0 ; i < N ; i++){
        scanf("%lld", &a[i]);
    }
    solve(N, move(a));
    return 0;
}
