#include <bits/stdc++.h>
#include <atcoder/all>

using namespace std;
using namespace atcoder;

using ll = long long;

const ll MOD = 998244353;
using mint = static_modint<MOD>;

void solve(ll N){
    ll x;
	mint r = 1;
	x = N;
	while (x) {
		x /= 10;
		r *= mint(10);
	}

	mint ans = mint(N) * (r.pow(N) - mint(1)) * ((r - mint(1)).inv());
	cout << (ans.val()) << endl;
}

// Generated by 2.14.0 https://github.com/kyuridenamida/atcoder-tools
int main(){
    ll N;
    scanf("%lld", &N);
    solve(N);
    return 0;
}
